import { FC } from 'react';
import Head from 'next/head';

const Index: FC = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="color-scheme" content="light only" />
                {/* {isDevelopmentHost && <meta name="robots" content="noindex,nofollow" />} */}

                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
                <link rel="shortcut icon" href="/favicon.ico" />
                <link rel="icon" href="/favicon.svg" />
                <link rel="manifest" href="/manifest.json" />

                {/* <meta property="og:title" content="Плед, какао и волшебные карты" />
                <meta property="og:type" content="website" />
                <meta name="twitter:card" content="summary_large_image" />
                <meta property="og:image" content="/image.jpg" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="630" />
                <meta property="og:url" content="https://2023.samokat.ru/" />
                <meta property="og:description" content="Запускаем большой новогодний розыгрыш призов" /> */}
            </Head>
            <main>Index</main>
        </>
    );
};

export default Index;
